# Generated by Django 5.0.4 on 2024-04-25 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0002_alter_user_email_alter_user_username"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("license", models.ImageField(upload_to="restaurants/license")),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.profile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpeningHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (1, "MONDAY"),
                            (2, "TUESDAY"),
                            (3, "WEDNESDAY"),
                            (4, "THURSDAY"),
                            (5, "FRIDAY"),
                            (6, "SATURDAY"),
                            (7, "SUNDAY"),
                        ]
                    ),
                ),
                (
                    "from_hour",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("12:00 AM", "12:00 AM"),
                            ("12:30 AM", "12:30 AM"),
                            ("01:00 AM", "01:00 AM"),
                            ("01:30 AM", "01:30 AM"),
                            ("02:00 AM", "02:00 AM"),
                            ("02:30 AM", "02:30 AM"),
                            ("03:00 AM", "03:00 AM"),
                            ("03:30 AM", "03:30 AM"),
                            ("04:00 AM", "04:00 AM"),
                            ("04:30 AM", "04:30 AM"),
                            ("05:00 AM", "05:00 AM"),
                            ("05:30 AM", "05:30 AM"),
                            ("06:00 AM", "06:00 AM"),
                            ("06:30 AM", "06:30 AM"),
                            ("07:00 AM", "07:00 AM"),
                            ("07:30 AM", "07:30 AM"),
                            ("08:00 AM", "08:00 AM"),
                            ("08:30 AM", "08:30 AM"),
                            ("09:00 AM", "09:00 AM"),
                            ("09:30 AM", "09:30 AM"),
                            ("10:00 AM", "10:00 AM"),
                            ("10:30 AM", "10:30 AM"),
                            ("11:00 AM", "11:00 AM"),
                            ("11:30 AM", "11:30 AM"),
                            ("12:00 PM", "12:00 PM"),
                            ("12:30 PM", "12:30 PM"),
                            ("01:00 PM", "01:00 PM"),
                            ("01:30 PM", "01:30 PM"),
                            ("02:00 PM", "02:00 PM"),
                            ("02:30 PM", "02:30 PM"),
                            ("03:00 PM", "03:00 PM"),
                            ("03:30 PM", "03:30 PM"),
                            ("04:00 PM", "04:00 PM"),
                            ("04:30 PM", "04:30 PM"),
                            ("05:00 PM", "05:00 PM"),
                            ("05:30 PM", "05:30 PM"),
                            ("06:00 PM", "06:00 PM"),
                            ("06:30 PM", "06:30 PM"),
                            ("07:00 PM", "07:00 PM"),
                            ("07:30 PM", "07:30 PM"),
                            ("08:00 PM", "08:00 PM"),
                            ("08:30 PM", "08:30 PM"),
                            ("09:00 PM", "09:00 PM"),
                            ("09:30 PM", "09:30 PM"),
                            ("10:00 PM", "10:00 PM"),
                            ("10:30 PM", "10:30 PM"),
                            ("11:00 PM", "11:00 PM"),
                            ("11:30 PM", "11:30 PM"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "to_hour",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("12:00 AM", "12:00 AM"),
                            ("12:30 AM", "12:30 AM"),
                            ("01:00 AM", "01:00 AM"),
                            ("01:30 AM", "01:30 AM"),
                            ("02:00 AM", "02:00 AM"),
                            ("02:30 AM", "02:30 AM"),
                            ("03:00 AM", "03:00 AM"),
                            ("03:30 AM", "03:30 AM"),
                            ("04:00 AM", "04:00 AM"),
                            ("04:30 AM", "04:30 AM"),
                            ("05:00 AM", "05:00 AM"),
                            ("05:30 AM", "05:30 AM"),
                            ("06:00 AM", "06:00 AM"),
                            ("06:30 AM", "06:30 AM"),
                            ("07:00 AM", "07:00 AM"),
                            ("07:30 AM", "07:30 AM"),
                            ("08:00 AM", "08:00 AM"),
                            ("08:30 AM", "08:30 AM"),
                            ("09:00 AM", "09:00 AM"),
                            ("09:30 AM", "09:30 AM"),
                            ("10:00 AM", "10:00 AM"),
                            ("10:30 AM", "10:30 AM"),
                            ("11:00 AM", "11:00 AM"),
                            ("11:30 AM", "11:30 AM"),
                            ("12:00 PM", "12:00 PM"),
                            ("12:30 PM", "12:30 PM"),
                            ("01:00 PM", "01:00 PM"),
                            ("01:30 PM", "01:30 PM"),
                            ("02:00 PM", "02:00 PM"),
                            ("02:30 PM", "02:30 PM"),
                            ("03:00 PM", "03:00 PM"),
                            ("03:30 PM", "03:30 PM"),
                            ("04:00 PM", "04:00 PM"),
                            ("04:30 PM", "04:30 PM"),
                            ("05:00 PM", "05:00 PM"),
                            ("05:30 PM", "05:30 PM"),
                            ("06:00 PM", "06:00 PM"),
                            ("06:30 PM", "06:30 PM"),
                            ("07:00 PM", "07:00 PM"),
                            ("07:30 PM", "07:30 PM"),
                            ("08:00 PM", "08:00 PM"),
                            ("08:30 PM", "08:30 PM"),
                            ("09:00 PM", "09:00 PM"),
                            ("09:30 PM", "09:30 PM"),
                            ("10:00 PM", "10:00 PM"),
                            ("10:30 PM", "10:30 PM"),
                            ("11:00 PM", "11:00 PM"),
                            ("11:30 PM", "11:30 PM"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "Restaurants",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ("day", "-from_hour"),
                "unique_together": {("Restaurants", "day", "from_hour", "to_hour")},
            },
        ),
    ]
