# Generated by Django 5.0.4 on 2024-05-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
