# Generated by Django 5.0.4 on 2024-05-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("USER", "User"),
                    ("RESTAURANT", "Restaurant"),
                ],
                default="USER",
                max_length=10,
            ),
        ),
    ]
